services:
  #=============================================================================================================
  # POSTGRESQL
  #
  # Referência:
  # - https://www.postgresql.org/docs/
  # - https://hub.docker.com/_/postgres
  # - https://github.com/postgres/postgres
  #=============================================================================================================
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    read_only: false
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPass
      - POSTGRES_DB=manager
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 3