server:
    port: 3003
    servlet:
        context-path: /webhook

spring:
    application:
        name: parking-manager

    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/manager}
        username: ${SPRING_DATASOURCE_USERNAME:postgresUser}
        password: ${SPRING_DATASOURCE_PASSWORD:postgresPass}
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            connection-timeout: 30000
            minimum-idle: 5
            idle-timeout: 30000
            max-lifetime: 1800000

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                jdbc:
                    lob:
                        non_contextual_creation: true

    security:
        basic:
            enabled: false
        user:
            name: none
            password: none

    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

    openapi:
        dev-url: http://localhost:3003/webhook
        local-url: http://localhost:3003/webhook

    liquibase:
        change-log: db/changelog/db.changelog-master.xml

logging:
    level:
        org.springframework: INFO
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE